# Generated by Django 2.2 on 2019-06-01 07:40

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='pubished',
            new_name='published',
        ),
    ]
