# Generated by Django 2.2 on 2019-06-02 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('main', '0003_auto_20190602_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 15, 5, 14, 552268), verbose_name='date published'),
        ),
    ]
