# Generated by Django 2.2 on 2019-06-02 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('main', '0004_auto_20190602_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 15, 21, 21, 74561), verbose_name='date published'),
        ),
    ]
