# Generated by Django 2.2 on 2019-06-02 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('main', '0005_auto_20190602_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='tut_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 15, 25, 57, 598518), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tut_series',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Series', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tut_slug',
            field=models.CharField(default='', max_length=200),
        ),
    ]
