# Generated by Django 2.2 on 2019-06-02 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('main', '0007_auto_20190602_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TutorialCategory',
        ),
        migrations.RenameModel(
            old_name='Series',
            new_name='TutorialSeries',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='content',
            new_name='tutorial_content',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tut_series',
            new_name='tutorial_series',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tut_slug',
            new_name='tutorial_slug',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='title',
            new_name='tutorial_title',
        ),
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='cat_slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='cat_summary',
            new_name='category_summary',
        ),
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='tut_category',
            new_name='tutorial_category',
        ),
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='ser_summary',
            new_name='series_summary',
        ),
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='tut_category',
            new_name='tutorial_category',
        ),
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='tut_series',
            new_name='tutorial_series',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='published',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 15, 47, 14, 41650), verbose_name='date published'),
        ),
    ]
