# Generated by Django 2.2 on 2019-06-02 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('main', '0010_auto_20190602_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 16, 8, 46, 981779), verbose_name='date published'),
        ),
    ]
