# Generated by Django 2.2 on 2019-06-02 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('main', '0011_auto_20190602_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TutorialCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='TutorialSeries',
            new_name='Series',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='cat_slug',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_summary',
            new_name='cat_summary',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='tutorial_category',
            new_name='tut_category',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='series_summary',
            new_name='ser_summary',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='tutorial_category',
            new_name='tut_category',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='tutorial_series',
            new_name='tut_series',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_series',
            new_name='tut_series',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_slug',
            new_name='tut_slug',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_published',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 16, 21, 43, 648017), verbose_name='date published'),
        ),
    ]
